INSERT INTO reviews (product_id, user_id, stars, title, text)
VALUES
(4, 1, 3, 'Very Happy','Worked like a dream! I would definitely use it if I needed a lawn mower again!'),
(1, 3, 5, 'Awesome','THE BEST EVER!'),
(5, 2, 1, 'Disappointing','This was the worst. I hated it'),
(2, 6, 3, 'Okay','underwhelming but fine'),
(3, 5, 2, 'Terrible','The only reason I didnt give it a one is the owner was cute'),
(6, 4, 5, 'Works','Amazing!'),
(7, 1, 2, 'My Favorite','Top ten products'),
(8, 3, 4, 'Worked for me','Worked for the job I was doing'),
(9, 1, 4, 'No issues','That worked so well! It was a little dirty when I picked it up though'),
(10, 5, 5, 'Perfect Fit','Just what I needed!'),
(10, 6, 5, 'So simple','Worked so well for me, totally worked, will rent again!'),
(10, 3, 2, 'No five stars','Almost perfect, a little scratch on it!'),
(10, 4, 2, 'My dog liked it','My dog says woof woof woof!'),
(11, 6, 4, 'Great','Worked great!'),
(12, 2, 3, 'So Simple','It was fine'),
(13, 1, 5, 'Blown Away','I was blown away by how amazing it was'),
(14, 4, 4, 'Snazzy','They went great with my dress'),
(15, 5, 3, 'Fine','Poutine green juice leggings unicorn four dollar toast'),
(16, 2, 5, 'The Best!','Bitters tumeric offal, listicle echo park hexagon tousled seitan polaroid cold-pressed pop-up williamsburg.'),
(17, 2, 4, 'Wow!','Cloud bread adaptogen vegan drinking vinegar hoodie tacos humblebrag.'),
(18, 1, 3, 'So Average','Celiac selvage taiyaki put a bird on it bitters gluten-free.'),
(19, 2, 4, 'Yup. It exists','Farm-to-table crucifix try-hard vegan.'),
(20, 6, 2, 'Ew','Before they sold out quinoa viral thundercats food truck literally chia.'),
(1, 4, 3, 'Okay','Activated charcoal hammock retro +1.'),
(2, 5, 4, 'Amazed','Cardigan +1 etsy activated charcoal af. Bushwick biodiesel pinterest selfies waistcoat vinyl.'),
(3, 6, 3, 'The Okayest Experience','Chillwave echo park PBR&B kickstarter, etsy four loko venmo helvetica hashtag viral.'),
(4, 2, 4, 'Keep in mind...','Keytar iPhone humblebrag 90s, pop-up migas unicorn man bun locavore banh mi.'),
(5, 2, 2, 'Never again','Mixtape messenger bag lomo slow-carb, typewriter cardigan whatever coloring book.'),
(6, 1, 5, 'YAY!','Sustainable unicorn lyft, small batch pok pok chartreuse retro craft beer church-key.'),
(7, 2, 4, 'Dude','Mlkshk fashion axe street art microdosing.'),
(8, 3, 1, 'Super duper gross','Tattooed pour-over shaman glossier, vaporware synth franzen literally mustache skateboard.'),
(9, 2, 4, 'Hooray','Brunch four loko vape authentic hot chicken banh mi, kickstarter brooklyn echo park messenger bag wolf plaid.'),
(10, 4, 3, 'Ho hum','Scenester af master cleanse cliche prism green juice, swag dreamcatcher typewriter unicorn listicle viral.'),
(11, 1, 4, 'Would do it again','Try-hard deep v echo park flannel bitters hoodie.'),
(12, 5, 5, 'THE BEST THING EVER','Swag palo santo wolf DIY raclette kombucha synth flannel, mustache unicorn.'),
(13, 5, 4, 'Exceeded Expectations','Bicycle rights banh mi iceland pickled actually. '),
(14, 2, 3, 'Um, Maybe ok','Cronut palo santo chartreuse put a bird on it air plant twee tumeric beard church-key tattooed heirloom.'),
(15, 3, 2, 'Sure','Before they sold out actually normcore, air plant lo-fi coloring book polaroid 8-bit four dollar toast ugh synth la croix sustainable YOLO.'),
(16, 2, 4, 'My fave','Enamel pin literally craft beer cred skateboard blue bottle shabby chic chambray meggings unicorn drinking vinegar banh mi hexagon.'),
(17, 3, 5, 'Fave in the world','Four loko everyday carry af 8-bit tofu meggings lo-fi succulents cloud bread.'),
(18, 4, 4, 'So cute','Seitan poutine 90s kale chips man bun activated charcoal.'),
(19, 3, 5, 'Awwww','Pabst palo santo subway tile lumbersexual dreamcatcher, celiac gentrify tacos kinfolk freegan plaid snackwave.'),
(20, 6, 4, 'Well Dang','Four loko celiac pok pok yuccie chicharrones gastropub bushwick single-origin coffee before they sold out wayfarers.'),
(1, 5, 3, 'Sure','Pug yuccie chicharrones leggings hot chicken enamel pin.'),
(2, 3, 3, 'Uh-huh', 'Shoreditch migas tacos organic tattooed vice authentic austin.'),
(3, 2, 4, 'Wowzer!', 'Chambray lo-fi art party actually, VHS street art tumeric asymmetrical fanny pack messenger bag kitsch.'),
(4, 4, 4, 'oh Yay!', 'Biodiesel chartreuse post-ironic cold-pressed pok pok freegan poutine health goth bitters etsy.'),
(5, 2, 1, 'SUPER GROTTY','Deep v post-ironic knausgaard, 90s readymade meggings iceland tofu kinfolk.'),
(6, 2, 4, 'Oh Yeah!','Gastropub hammock slow-carb viral.'),
(7, 1, 5, 'Superb','Aesthetic la croix microdosing single-origin coffee iceland master cleanse vegan vaporware whatever blue bottle neutra hammock try-hard.'),
(8, 1, 4, 'Astounding','Godard waistcoat everyday carry, kogi tbh vinyl cronut organic church-key meh man braid locavore pug.'),
(9, 2, 1, 'Jaw-droppingly Stupid','Green juice forage succulents drinking vinegar truffaut tilde freegan ramps keffiyeh edison bulb disrupt.'),
(10, 3, 2, 'Girl, no','Single-origin coffee copper mug hella live-edge iceland heirloom subway tile dreamcatcher kale chips roof party ugh pitchfork iPhone.'),
(11, 2, 3, 'Average','Biodiesel vice lyft cred keffiyeh pinterest narwhal kickstarter gluten-free celiac pickled.'),
(12, 6, 4, 'Yup it works!','Ugh keytar coloring book chambray forage street art health goth cold-pressed plaid art party.'),
(13, 5, 2, 'Ick','DIY edison bulb subway tile, fingerstache readymade XOXO heirloom hashtag ennui schlitz plaid iceland small batch meditation.'),
(14, 2, 4, 'Hooray!','Etsy normcore lyft literally, wayfarers coloring book taxidermy poutine migas biodiesel.'),
(15, 3, 3, 'not ideal, but it was there','Blue bottle echo park brunch etsy.'),
(16, 2, 4, 'Absurdly good','Chicharrones +1 paleo single-origin coffee tumblr fam truffaut chartreuse 8-bit flexitarian cardigan taxidermy shaman.'),
(17, 2, 5, 'Stupendous','Organic enamel pin franzen, pork belly neutra mumblecore gentrify.'),
(18, 1, 3, 'Like lukewarm water after a run','Sriracha portland selfies, pok pok snackwave ennui tousled.'),
(19, 2, 3, 'sure','Freegan activated charcoal hella, synth stumptown ennui thundercats wolf lomo organic franzen mlkshk vape fingerstache.'),
(20, 1, 4, 'Yay!','Irony narwhal kogi, tumblr shabby chic blue bottle unicorn wolf.');